namespace MapleKiosk.Web.Services;

/// <summary>
/// What search engines are told about each film the pages play (schema.org VideoObject, written by
/// <see cref="Components.Sections.VideoSchema"/>). The films only load when clicked, so without this a
/// crawler sees a page with no video. Title, first paragraph of the description, upload time and length
/// come from the Maple Kiosk YouTube channel; a film with no description there has one written here.
/// Add a film's entry when a page starts playing it.
/// </summary>
public static class SiteVideos
{
    public sealed record Video(string Id, string Title, string Description, string Uploaded, int Seconds);

    public static Video? Find(string? id) => id is not null && All.TryGetValue(id, out var v) ? v : null;

    private static readonly Dictionary<string, Video> All = new Video[]
    {
        new("xVtDXOWpXC8", "Gift cards that bring in new clients | MapleSPA",
            "A guest buys a gift card for a friend. The friend walks into your salon and pays with it, and you have a new client. This film follows a MapleSPA gift card from the order to the printed card, loading it at the front desk, and paying with it at checkout.",
            "2026-10-07T05:04:02Z", 97),
        new("Rk4OQA2B2SQ", "Thẻ quà tặng in tên tiệm: khách mua tặng bạn, bạn tới tiệm xài | MapleSPA",
            "Anh chị muốn khách mua thẻ quà tặng của tiệm, đem tặng bạn bè, rồi bạn bè tới tiệm làm nail? Chị My chỉ trọn vòng đời một tấm thẻ quà tặng với MapleSPA, có quay thật tại quầy của một tiệm nail.",
            "2026-10-06T03:23:00Z", 97),
        new("IdRUCewVV3E", "Подарочные карты с логотипом салона: гость дарит, друг приходит | MapleSPA",
            "Хотите, чтобы гости покупали подарочные карты вашего салона и дарили их друзьям, а друзья приходили к вам? Ми показывает весь путь подарочной карты в MapleSPA, с настоящей съёмкой у стойки салона.",
            "2026-10-06T06:05:14Z", 109),
        new("-MW2ir_vs2o", "Fast Cafe Checkout and Tips Without the Awkward Moment | MapleCoffee",
            "Spinning the screen around, the awkward tip question, digging for change: checkout shouldn't be the slowest part of the visit.",
            "2026-10-02T04:27:36Z", 74),
        new("190OK7pMQqA", "Changez un prix une fois, partout | MaplePOS",
            "Vous montez un seul prix, et le menu papier, le menu QR, la tablette du serveur et le tableau se contredisent. Et vous réimprimez des menus. Encore.",
            "2026-10-03T05:30:45Z", 76),
        new("1o9EnqKohno", "Khách walk-in và khách đi nhóm: đông mà vẫn gọn",
            "Thứ Bảy đông khách. Khách walk-in hỏi chờ bao lâu mà hông ai trả lời được, rồi nhóm bốn người tới cùng lúc.",
            "2026-10-01T16:12:04Z", 59),
        new("2Q9yaKK-glk", "Мастера спорят, чья очередь? Turn board в MapleSPA",
            "Субботнее утро, клиенты идут без перерыва, а мастера спорят, чья очередь. Знакомо?",
            "2026-10-03T08:54:59Z", 69),
        new("2SLdSOflvIM", "An assistant that books your tables day and night | MaplePOS",
            "Friday night: the phone rings, your hands are full of plates, and the caller hangs up. After close, it goes to voicemail.",
            "2026-10-03T06:34:32Z", 77),
        new("5Mo5EY5fgyM", "Клиенты без записи и группы: полный салон без хаоса",
            "Суббота, полный салон. Клиент без записи спрашивает, сколько ждать, а тут ещё компания из четырёх человек.",
            "2026-10-03T15:30:03Z", 68),
        new("5qKT4qKsU40", "L'addition en quelques secondes, le pourboire sans malaise | MaplePOS",
            "Le repas était parfait. Puis on attend l'addition, on attend le terminal, et quelqu'un reste planté là pendant qu'on choisit le pourboire.",
            "2026-10-03T05:27:09Z", 76),
        new("71u7Ylsjf_s", "Fair tips and payroll in minutes | MaplePOS",
            "Close: the tips are on the table, everyone's counting, and nobody agrees. Then Sunday night, it's you, a calculator and a stack of timesheets.",
            "2026-10-03T06:39:14Z", 72),
        new("9zb8QVRBdgg", "MapleGarage in brief (animated)",
            "An animated walk through a day at an independent garage with MapleGarage: the repair request, the booking, check-in, the quote, the shop board and the bill.",
            "2026-10-06T13:26:08Z", 92),
        new("aC6QGrsEQ9c", "MapleKiosk AI voice agent",
            "The MapleKiosk AI voice agent answers the business's phone, takes bookings and orders, and answers questions about services and hours.",
            "2026-09-30T09:41:39Z", 81),
        new("bW4pK_uNf3Q", "Pourboires justes et paie en quelques minutes | MaplePOS",
            "La fermeture : les pourboires sont sur la table, tout le monde compte, et personne n'est d'accord. Puis dimanche soir, c'est vous, une calculatrice et une pile de feuilles de temps.",
            "2026-10-03T05:28:54Z", 80),
        new("DOrVkwVhBVQ", "Beat the Morning Rush: Right Drink, Right Name, Every Time | MapleCoffee",
            "Eight in the morning. The line's out the door, orders are scribbled on cups, and nobody knows whose latte is whose.",
            "2026-10-02T04:24:52Z", 68),
        new("dvio2Pc7DQQ", "MaplePOS : tout votre restaurant, une seule salle",
            "Gérer un restaurant, c'est beaucoup : le rush du vendredi, les réservations, l'addition, le partage des pourboires. En moins d'une minute, Rosa vous montre comment MaplePOS réunit tout ça.",
            "2026-10-03T04:24:13Z", 56),
        new("dwXwTZY2cGA", "MapleCoffee: Your Whole Café, One Screen",
            "Running a café is a lot: the morning rush, the till, the tips, the regulars. MapleCoffee brings it all together in one system built for independent coffee shops.",
            "2026-10-02T04:21:22Z", 38),
        new("ePsVx2Hy4iE", "ИИ-администратор отвечает на звонки за ваш салон",
            "Мастер делает маникюр, и тут звонит телефон. Возьмёт трубку, и ждёт клиентка в кресле. Не возьмёт, и салон теряет нового клиента.",
            "2026-10-03T15:26:59Z", 89),
        new("evf6wCDIirE", "Kitchen and floor in sync, no more shouting \"order up\" | MaplePOS",
            "\"Order up!\" shouted into a full room, tickets lost on the rail, plates going cold at the pass.",
            "2026-10-03T06:32:49Z", 70),
        new("f8ZeusLsGAM", "Turn First-Timers Into Regulars: Café Loyalty and Gift Cards | MapleCoffee",
            "Most first-timers never come back, and you never even learn their name. Paper stamp cards get lost, and a regular looks just like a stranger.",
            "2026-10-02T04:27:58Z", 72),
        new("for6OTc911k", "The Job Reaches You Before the Car Does: Repair Requests | MapleGarage",
            "A rock cracks Hana's windshield on the highway. She messages Kai's shop, and before her car ever rolls in, Kai already has the problem, the photos, an approved price and a booked day.",
            "2026-10-06T14:24:04Z", 87),
        new("G3ENTSur3ik", "Commande par code QR, dans la langue de chaque client | MaplePOS",
            "Vos clients sont prêts à commander, prêts pour le dessert, prêts à payer, mais ils attendent un serveur, et certains ne peuvent pas lire le menu.",
            "2026-10-03T04:25:05Z", 76),
        new("g5qjmIv-xnY", "No more double bookings: the MaplePOS reservation book",
            "Saturday night: a pencil book full of crossed-out names, two parties booked at the same table, and walk-ins guessing the wait.",
            "2026-10-03T06:37:28Z", 79),
        new("G5uLNWY26ds", "Just Say It: A Voice-Ordering Kiosk That Speaks Your Guest's Language | MapleCoffee",
            "One guest who can't decide holds up the line, and a visitor who doesn't speak English takes even longer.",
            "2026-10-02T04:26:36Z", 75),
        new("GwhcO3sguvw", "Khuyến mãi đo được: biết chỗ nào kéo khách về",
            "Thứ Ba vắng khách, thợ ngồi chơi. Anh chị đăng khuyến mãi lên mạng mà hông biết bài nào thiệt sự kéo khách về.",
            "2026-10-01T16:11:44Z", 52),
        new("hcGvxU58y2w", "Nhận hẹn online 24/7: tiệm đóng cửa vẫn có khách đặt",
            "Mười một giờ đêm, khách muốn đặt hẹn cho ngày mai. Tiệm đóng cửa, gọi hoài hông ai bắt máy, khách đi tiệm khác.",
            "2026-10-01T16:13:30Z", 60),
        new("hJiZ4VKCFok", "The bill in seconds, tips without the awkward | MaplePOS",
            "The meal was perfect. Then the wait for the bill, the wait for the card machine, and someone hovering while you pick the tip.",
            "2026-10-03T06:38:25Z", 70),
        new("hxv4R9S6c5w", "Tính lương thợ nail vài phút, hông còn thức khuya",
            "Tối Chủ nhật ngồi cộng từng tờ ticket, tính phần trăm cho từng thợ, cộng tới khuya mà vẫn sợ sai.",
            "2026-10-01T16:14:18Z", 66),
        new("IDm_50EGFVk", "Клиентка присылает фото ногтей и сразу получает совет",
            "Клиентка смотрит на свои ногти и не знает, что выбрать. Спросить стесняется, а потом уходит в другой салон.",
            "2026-10-03T15:43:24Z", 68),
        new("lcFLmIvngU4", "MapleGarage en bref (animation)",
            "Une journée dans un garage indépendant avec MapleGarage, en animation : la demande de réparation, le rendez-vous, la réception, la soumission, le tableau de l'atelier et la facture.",
            "2026-10-06T13:30:10Z", 103),
        new("n1Src-4w5MY", "Lễ tân AI nghe điện thoại, đặt hẹn giùm tiệm nail",
            "Đang làm móng cho khách thì điện thoại reng. Bắt máy thì khách trên ghế phải chờ, hông bắt thì mất khách mới.",
            "2026-10-01T16:12:31Z", 81),
        new("nvqCqa6-6ow", "Un assistant qui prend vos réservations jour et nuit | MaplePOS",
            "Vendredi soir : le téléphone sonne, vous avez les mains pleines d'assiettes, et la personne raccroche. Après la fermeture, c'est la boîte vocale.",
            "2026-10-03T05:24:37Z", 90),
        new("OKK5rJ-9o60", "Расчёт за секунды: чаевые, подарочные карты и оплата картой",
            "Час пик, у кассы очередь. Кто-то платит подарочной картой, кто-то делит чаевые, и калькулятор уже не спасает.",
            "2026-10-03T15:39:32Z", 56),
        new("p701-06Dhqo", "QR ordering in every guest's language | MaplePOS",
            "Your guests are ready to order, ready for dessert, ready to pay, but they're waiting to catch a server, and some can't read the menu.",
            "2026-10-03T06:31:42Z", 72),
        new("pFyeySzUjl0", "Зарплата мастеров за минуты, а не за ночь",
            "Воскресный вечер, стопка чеков и калькулятор. Считаете процент каждому мастеру до ночи и всё равно боитесь ошибиться.",
            "2026-10-03T15:40:37Z", 73),
        new("PIgmafCS_Fo", "End the Friday-night chaos: the MaplePOS floor board",
            "Friday, 7 p.m. Plates are dying under the heat lamp, someone's waving for the bill, and nobody knows who's on table 12.",
            "2026-10-03T06:30:26Z", 68),
        new("pO7CuFU-pm8", "Thợ cãi nhau giành lượt? Turn board của MapleSPA",
            "Sáng thứ Bảy đông khách, thợ cãi nhau coi tới lượt ai, bảng ghi tay bôi xóa tùm lum.",
            "2026-10-01T16:13:10Z", 62),
        new("PvruNdaH_C4", "MapleSPA: весь салон на одном экране",
            "Очередь мастеров, онлайн-запись, звонки, расчёт, зарплата и акции: в MapleSPA всё это в одной системе. Ми за минуту покажет, как салон работает без бумажек, доски с записями и пяти разных приложений.",
            "2026-10-03T15:23:53Z", 54),
        new("Q11LB20gRlY", "Fini le chaos du vendredi soir : le plan de salle MaplePOS",
            "Vendredi, 19 h. Les assiettes refroidissent sous la lampe, quelqu'un réclame l'addition, et personne ne sait qui s'occupe de la table 12.",
            "2026-10-03T04:23:33Z", 74),
        new("r-MfbErVfjA", "Change a Price Once and It's Right Everywhere | MapleCoffee",
            "You raised a price last week. Now the till says one thing, the menu board says another, and you're reprinting paper menus. Again. And when someone asks who changed it and when, nobody remembers.",
            "2026-10-02T04:29:16Z", 64),
        new("Rhe8uYCOzxU", "Turn first-time guests into regulars | MaplePOS",
            "They loved dinner, they promised to come back, and you never saw them again. And when a regular does return, nobody remembers her allergy.",
            "2026-10-03T06:40:35Z", 68),
        new("rOqKCAwLaY0", "Change a price once, everywhere | MaplePOS",
            "You raise one price, and now the paper menu, the QR menu, the server's tablet and the menu board disagree. And you're reprinting menus. Again.",
            "2026-10-03T06:41:45Z", 70),
        new("sQG1-vK-Zn4", "Tip Sharing in MapleCoffee: How It Works and How to Set It Up",
            "Share tips fairly among everyone who's working, without a spreadsheet. In under three minutes, Alvin shows café owners how MapleCoffee splits tips and how to set it up right the first time.",
            "2026-10-03T07:43:08Z", 164),
        new("SQOIlX99CJc", "Tính tiền vài giây: tip, thẻ quà tặng, quẹt thẻ",
            "Giờ cao điểm, khách xếp hàng chờ tính tiền. Người trả thẻ quà tặng, người chia tip, bấm máy tính muốn rối.",
            "2026-10-01T16:14:40Z", 51),
        new("t1_a_Nac8wA", "MapleGarage overview",
            "A garage day in MapleGarage: booking, check-in with photos and signature, job-by-job quotes, the live shop board, technician job lists, parts and the bill.",
            "2026-09-27T09:28:23Z", 88),
        new("UbmRsBF2aNI", "MapleSPA: quản lý cả tiệm nail trên một màn hình",
            "Lượt thợ, đặt hẹn online, nghe điện thoại, tính tiền, tính lương và khuyến mãi: MapleSPA gom hết vô một chỗ. Chị My giới thiệu trong một phút cách tiệm chạy gọn mà hông cần giấy, bảng ghi tay hay năm cái app khác nhau.",
            "2026-10-01T16:12:51Z", 47),
        new("UO_YqWy5gIA", "Fini les doubles réservations : le carnet MaplePOS",
            "Samedi soir : le carnet est plein de ratures, deux groupes sont réservés à la même table, et à l'entrée, on devine chaque attente.",
            "2026-10-03T05:26:04Z", 88),
        new("VFIstuRr1d0", "Split Tips Fairly and Get Payday Done in Minutes | MapleCoffee",
            "Sunday night: the tip jar's on the table, the hours are on sticky notes, and payroll is a calculator and a headache. And somebody always feels shortchanged.",
            "2026-10-02T04:28:49Z", 65),
        new("VHmvhSuSo38", "Акции, результат которых видно: какая реклама приводит клиентов",
            "Вторник, клиентов нет. Вы публикуете акции в соцсетях, но не знаете, какая из них действительно работает.",
            "2026-10-03T15:41:29Z", 56),
        new("weVV7Fn8XGM", "Онлайн-запись 24/7: клиенты записываются, пока салон закрыт",
            "Одиннадцать вечера. Клиентка хочет записаться на завтра, звонит, но салон закрыт, и она уходит в другой.",
            "2026-10-03T15:26:12Z", 64),
        new("x0g8J87PY9s", "Transformez les nouveaux clients en habitués | MaplePOS",
            "Ils ont adoré le souper, ils ont promis de revenir, et vous ne les avez jamais revus. Et quand une habituée revient, personne ne se souvient de son allergie.",
            "2026-10-03T05:29:58Z", 74),
        new("yNZny11acfk", "MaplePOS: your whole restaurant, one floor",
            "Running a restaurant is a lot: the Friday push, the book, the bill, the tip-out. In under a minute, Rosa shows how MaplePOS brings it all together.",
            "2026-10-03T06:28:37Z", 52),
        new("YSUYnh1Z_jI", "Cuisine et salle en phase, sans crier « c'est prêt ! » | MaplePOS",
            "La cuisine crie dans une salle pleine, les bons se perdent sur le rail, et les plats refroidissent au passe.",
            "2026-10-03T04:35:37Z", 71),
        new("Zxsj4OQ8CCY", "A Second Till That Never Takes a Break: Kiosk + Online Ordering | MapleCoffee",
            "One till, one cashier, and a line to the door. Every guest who walks out is a sale you never see.",
            "2026-10-02T04:25:36Z", 68),
    }.ToDictionary(v => v.Id);
}
